version: '3'
services:
  my_expo_app:
    image: ${APP_NAME}
    ports:
        - "19000:19000"
        - "19001:19001"
        - "19002:19002"
    volumes:
         - ./src/:/usr/app/
    privileged: true
    devices:
      - /dev/tty4:/dev/tty4
    command: npm run android
